### ISSUE TITLE
how to use the intrinsics0.yaml and how to run stere depth estimation correctly

### ISSUE THREAD

**Issue by liangshunkun** [puzzlepaint/camera_calibration#58]
Hello, thank you very much for your work. 
I want to know how to use the intrinsics0.yaml, and I want to apply the calibrated results to my other algorithms. 
Also, I can't get the right results when I was using depth estimates. I wonder if there is a problem with my usage.Can you give me some instructions about how to run these programs correctly？

My calibration results are as follows ：
![image](https://user-images.githubusercontent.com/46750100/138583529-333b8a50-4a55-44cf-b140-11f641fc64e5.png)

the intrinsics0.yaml is the same as the intrinsic1.yaml. and the camera_tr_rig.yaml is as follows:

![image-20211024141944806](https://user-images.githubusercontent.com/46750100/138583550-4130046b-c3d9-4dad-88a3-0b29b2882f51.png)

Two images for depth estimation are as follows：

![image-20211024142247440](https://user-images.githubusercontent.com/46750100/138583552-c553c333-389c-44fe-84ef-5de52dc58569.png)

The results of stereo depth estimation obtained by me are as follows （but it is quite different from my expectation.）:

depth image:

![image-20211024142711315](https://user-images.githubusercontent.com/46750100/138583557-ab2ea857-ee5a-4196-9c43-93e35112112f.png)

point cloud:

![image-20211024142725886](https://user-images.githubusercontent.com/46750100/138583561-fba2b52a-4bbd-4a4b-9920-cae902debc18.png)

**Comment by liangshunkun** [comment]
Thank you very much for your reply. Because recently busy with courses, sorry did not reply you in time.
I have obtained the correct depth estimation results, but I do not know the principle very well.
I read the code in the project, but I cannot understand it at all.You used Patch Match Stereo to get disparity maps and "d = bf / x " to get depth results. But in fact the focal length f doesn 't exist in the generic camera model, and I ' m very confused about it. 
Can you briefly explain the principle of getting depth values ? Or give some instructions, such as some papers. 
Thank you again for your work.

**Comment by puzzlepaint** [comment]
> You used Patch Match Stereo to get disparity maps and "d = bf / x " to get depth results.

**Comment by puzzlepaint** [comment]
> You used Patch Match Stereo to get disparity maps and "d = bf / x " to get depth results.

No, actually the Patch Match Stereo implementation determines *inverse depths* directly rather than disparities. The inverse depths only need to be inverted (`depth = 1 / inverse_depth`) to get the actual depth values, without involving the baseline or focal length (the latter is anyway not a parameter that is estimated by the generic camera models).

The reason for using inverse depths instead of actual depth values is that they behave more similar to disparities, yielding a better distribution of values compared to actual depths: For example, imagine that in a given stereo configuration, the depth values from 10 meters to infinity (which is a huge range) might (depending on the relative pose of the cameras etc.) correspond to a tiny disparity shift in the stereo image, whereas the depth values from 0 meters to 10 meters might cause a much larger disparity shift. Using inverse depths instead, the mapping would be expected to be more even. This is because in the stereo-rectified case, disparity and inverse depths would only differ by the `baseline * focal_length` factor in a linear way. While this does not apply directly in case of having image distortion rather than a stereo-rectified case, it will still apply approximately in usual cases. (I realize this is not the clearest explanation, but I hope the idea was understandable anyway.)

The basic principle to estimate a depth (or analogously, inverse depth) value directly, without using disparities as in the stereo-rectified case, is actually rather simple: The calibrated camera models and the knowledge of the relative pose of the cameras allow for taking a pixel in one image, using some assumed (inverse) depth hypothesis for it, and transforming it to the other (stereo) image. This allows to check how similar the original pixel is to the corresponding pixel in the other (stereo) image. By testing this for a number of different depth hypotheses (in the Patch Match Stereo algorithm), the best depth hypothesis can be picked.
