### ISSUE TITLE
Issue with linking boost

### ISSUE THREAD

**Issue by ceinem** [puzzlepaint/camera_calibration#64]
Hi, 
at the very end of building everything I get an error regarding boost and haven't managed to figure it out. 

```
[100%] Building CXX object applications/camera_calibration/CMakeFiles/camera_calibration.dir/src/camera_calibration/main.cc.o
[100%] Building CXX object applications/camera_calibration/CMakeFiles/camera_calibration.dir/camera_calibration_autogen/mocs_compilation.cpp.o
[100%] Linking CXX executable camera_calibration
/usr/bin/ld: libcamera_calibration_baselib.so: undefined reference to `boost::filesystem::detail::directory_iterator_construct(boost::filesystem::directory_iterator&, boost::filesystem::path const&, unsigned int, boost::system::error_code*)'
/usr/bin/ld: libcamera_calibration_baselib.so: undefined reference to `boost::filesystem::detail::absolute(boost::filesystem::path const&, boost::filesystem::path const&, boost::system::error_code*)'
collect2: error: ld returned 1 exit status
make[3]: *** [applications/camera_calibration/CMakeFiles/camera_calibration.dir/build.make:132: applications/camera_calibration/camera_calibration] Error 1
make[2]: *** [CMakeFiles/Makefile2:865: applications/camera_calibration/CMakeFiles/camera_calibration.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:872: applications/camera_calibration/CMakeFiles/camera_calibration.dir/rule] Error 2
make: *** [Makefile:491: camera_calibration] Error 2
```

Does anyone have any advice on how to fix this/what's gone wrong? 
Thank you very much!

**Comment by puzzlepaint** [comment]
I am not sure, but I guess that this could for example be caused by different versions of the boost headers and libraries being present on the system, together with an incomplete configuration being done by the CMakeLists.txt files in the `camera_calibration` project, resulting in a mismatch that leads to those linker errors.

In principle, `camera_calibration_baselib` should be linked to the found boost libraries by this:
https://github.com/puzzlepaint/camera_calibration/blob/32173589ae4db7491ace3173b5bdf2bf65f98716/applications/camera_calibration/CMakeLists.txt#L186

And it should get the headers via this `PUBLIC` property:
https://github.com/puzzlepaint/camera_calibration/blob/32173589ae4db7491ace3173b5bdf2bf65f98716/CMakeLists.txt#L429

But perhaps it could be that one of them is not defined, potentially leading to the use of a different system-level version as implicit fallback, causing inconsistencies with some system environments. For example, some googling suggests that perhaps it should be `${BOOST_INCLUDE_DIRS}` instead of `${Boost_INCLUDE_DIR}`. To check this, one could insert debug messages such as `message(FATAL_ERROR "Debug: Boost headers: ${Boost_INCLUDE_DIR}")`.

**Comment by ceinem** [comment]
Hi, thanks for your reply. I tried to check the things you have mentioned, but couldn't find anything particular. Both `${BOOST_INCLUDE_DIRS}` and `${BOOST_INCLUDE_DIR}` return `/urs/include`, where boost is installed. 

I tried removing my whole boost installation and setting it up again, but this also didn't help. 

Do you think it might be a version problem? I'm running Ubuntu 20.04 with boost 1.71 installed from apt.

**Comment by puzzlepaint** [comment]
I don't think that it is a problem with boost 1.71. I just successfully built `camera_calibration` on my Ubuntu 20.04 system, and according to `ccmake` the boost-related variables are set as follows:

```
 Boost_DIR                        /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0
 Boost_FILESYSTEM_LIBRARY_RELEA   /usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.71.0
 Boost_INCLUDE_DIR                /usr/include
 Boost_SERIALIZATION_LIBRARY_RE   /usr/lib/x86_64-linux-gnu/libboost_serialization.so.1.71.0
 Boost_SYSTEM_LIBRARY_RELEASE     /usr/lib/x86_64-linux-gnu/libboost_system.so.1.71.0
```

My guess would still be that the build somehow uses the headers or libraries of a different boost version on your system, causing a mismatch. For example, I guess this could happen if there is also a boost install in `/usr/local/include` and this gets added to the list of include directories with higher priority than `/usr/include` (maybe due to a different library being used from there), but the build still links the libraries from the system install.

The paths used in the linker invocation can be checked by calling `make` in verbose mode, for example as follows:
```
VERBOSE=1 make -j8 camera_calibration
```

**Comment by ceinem** [comment]
Thanks for your help!! 
I'm not 100% sure what solved it in the end, but I got it to compile now. During feature extraction, I'm running into some CUDA issues, but that's another topic. The boost issues seem to be solved for now. Thanks again!
